### ISSUE TITLE
Debugger giving a refused connection error whenever binary interpreter has been modified with patchelf

### ISSUE THREAD

**Issue by tcheinen** [Vector35/debugger#136]
Hi!  I was testing out the debugger plugin with some CTF binaries and I found that it didn't work for most of them. I did some investigation to get a minimal case and the cause seems to be related to binaries which have had their interpreter modified using patchelf.  I've noticed that the gdbserver process is defunct which makes me suspect the issue has something to do with how gdbserver is invoked, but I tested and gdbserver does work with these binaries. 

```text
Traceback (most recent call last):
  File "/opt/binaryninja/plugins/../python/binaryninja/binaryview.py", line 2142, in _read
    data = self.perform_read(offset, length)
  File "/home/sky/.binaryninja/repositories/official/plugins/Vector35_debugger/ProcessView.py", line 167, in perform_read
    batch = adapter.mem_read(block, cache_len)
  File "/home/sky/.binaryninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 180, in mem_read
    return self.submit(lambda: self.adapter.mem_read(address, length))
  File "/home/sky/.binaryninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 84, in submit
    raise result
  File "/home/sky/.binaryninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 48, in worker
    self.results[index] = (True, job())
  File "/home/sky/.binaryninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 180, in <lambda>
    return self.submit(lambda: self.adapter.mem_read(address, length))
  File "/home/sky/.binaryninja/repositories/official/plugins/Vector35_debugger/gdblike.py", line 345, in mem_read
    reply = self.rspConn.tx_rx('m%x,%x' % (address, sz))
AttributeError: 'NoneType' object has no attribute 'tx_rx'
```
I have a minimal case (stub binary, libc, ld-linux) here. 
[bug.zip](https://github.com/Vector35/debugger/files/7033457/bug.zip)

**Comment by psifertex** [comment]
Thanks very much for the test-case. We're working on a total rewrite of the current debugger implementation so we'll definitely make sure to test these examples out and see how they do in the rewrite.

**Comment by tcheinen** [comment]
I investigated a little further and figured out the reason. The binary was set to look for a loader in the same directory using a relative path and so when invoked from whatever the working directory for binary ninja is it would fail. Easy enough to solve by patching the binary to use an absolute address, but I think the root cause is still worth fixing. IMO having the working directory of the debugged process be the directory the binary is in is more likely to be useful than having it inherit the working directory of the binary ninja process

**Comment by jeffli678** [comment]
Yeah thx for the investigation! We really should launch the target in the target's directory. We should also allow the user to specify a working directory
