### ISSUE TITLE
Crash on Linux while single stepping

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/debugger#310]
This does not happen reliably. It does not happen at all on some machines, and often on others. Tested on the x86_64 `helloworld` binary from the tests.

This was performed on a Threadripper with 32 cores at 4+GHz, so it is not caused by a slow machine.

The backtrace is as follows:

```
Thread 1 "binaryninja" received signal SIGSEGV, Segmentation fault.
BinaryNinjaDebuggerAPI::DebuggerController::GetLastIP (this=0x555500000066) at /home/rwagner/projects/binaryninja/public/debugger/api/debuggercontroller.cpp:599
599		return BNDebuggerGetLastIP(m_object);
(gdb) bt
#0  BinaryNinjaDebuggerAPI::DebuggerController::GetLastIP (this=0x555500000066)
    at /home/rwagner/projects/binaryninja/public/debugger/api/debuggercontroller.cpp:599
#1  0x00007fffbe2d9e67 in DebuggerUI::updateUI (this=0x55555a3191c0, event=...)
    at /home/rwagner/projects/binaryninja/public/debugger/api/debuggerapi.h:233
#2  0x00007fffec588d5f in void doActivate<false>(QObject*, int, void**) ()
   from /home/rwagner/Qt/6.3.1/gcc_64/lib/libQt6Core.so.6
#3  0x00007fffbe284f32 in DebuggerUI::debuggerEvent (this=<optimized out>, _t1=...)
    at /home/rwagner/projects/binaryninja/build/public/debugger/ui/debuggerui_autogen/EWIEGA46WW/moc_ui.cpp:219
#4  0x00007fffbe2e4663 in std::function<void (BinaryNinjaDebuggerAPI::DebuggerEvent const&)>::operator()(BinaryNinjaDebuggerAPI::DebuggerEvent const&) const (__args#0=..., this=0x5555599453b0)
    at /usr/include/c++/12.2.0/bits/std_function.h:591
#5  BinaryNinjaDebuggerAPI::DebuggerController::DebuggerEventCallback (ctxt=0x5555599453b0, event=0x555559364610)
    at /home/rwagner/projects/binaryninja/public/debugger/api/debuggercontroller.cpp:645
#6  0x00007fffd28b2d8e in operator() (event=..., __closure=0x7fffcc089780)
    at /home/rwagner/projects/binaryninja/public/debugger/core/ffi.cpp:815
#7  std::__invoke_impl<void, BNDebuggerRegisterEventCallback(BNDebuggerController*, void (*)(void*, BNDebuggerEvent*), char const*, void*)::<lambda(const BinaryNinjaDebugger::DebuggerEvent&)>&, const BinaryNinjaDebugger::DebuggerEvent&> (
    __f=...) at /usr/include/c++/12.2.0/bits/invoke.h:61
#8  std::__invoke_r<void, BNDebuggerRegisterEventCallback(BNDebuggerController*, void (*)(void*, BNDebuggerEvent*), char const*, void*)::<lambda(const BinaryNinjaDebugger::DebuggerEvent&)>&, const BinaryNinjaDebugger::DebuggerEvent&> (
    __fn=...) at /usr/include/c++/12.2.0/bits/invoke.h:111
#9  std::_Function_handler<void(const BinaryNinjaDebugger::DebuggerEvent&), BNDebuggerRegisterEventCallback(BNDebuggerController*, void (*)(void*, BNDebuggerEvent*), char const*, void*)::<lambda(const BinaryNinjaDebugger::DebuggerEvent&)> >::_M_invoke(const std::_Any_data &, const BinaryNinjaDebugger::DebuggerEvent &) (__functor=..., __args#0=...)
    at /usr/include/c++/12.2.0/bits/std_function.h:290
#10 0x00007fffd288cab2 in std::function<void (BinaryNinjaDebugger::DebuggerEvent const&)>::operator()(BinaryNinjaDebugger::DebuggerEvent const&) const (__args#0=..., this=0x7fffcc089780) at /usr/include/c++/12.2.0/bits/std_function.h:591
#11 operator() (__closure=0x7fffcc09bae0)
    at /home/rwagner/projects/binaryninja/public/debugger/core/debuggercontroller.cpp:1073
#12 std::__invoke_impl<void, BinaryNinjaDebugger::DebuggerController::PostDebuggerEvent(const BinaryNinjaDebugger::DebuggerEvent&)::<lambda()>&> (__f=...) at /usr/include/c++/12.2.0/bits/invoke.h:61
#13 std::__invoke_r<void, BinaryNinjaDebugger::DebuggerController::PostDebuggerEvent(const BinaryNinjaDebugger::DebuggerEvent&)::<lambda()>&> (__fn=...) at /usr/include/c++/12.2.0/bits/invoke.h:111
#14 std::_Function_handler<void(), BinaryNinjaDebugger::DebuggerController::PostDebuggerEvent(const BinaryNinjaDebugger::DebuggerEvent&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/12.2.0/bits/std_function.h:290
#15 0x00007fffd294fd03 in std::function<void ()>::operator()() const (this=0x7ffe7aafaf60)
    at /usr/include/c++/12.2.0/bits/std_function.h:591
#16 ExecuteActionLocal (ctxt=0x7ffe7aafaf60) at /home/rwagner/projects/binaryninja/api/mainthread.cpp:95
#17 0x00007fffee984139 in std::function<void ()>::operator()() const (this=0x7fffba800018)
    at /usr/include/c++/12.2.0/bits/std_function.h:591
#18 BinaryNinjaCore::MainThreadAction::Execute (this=0x7fffba800000)
    at /home/rwagner/projects/binaryninja/core/mainthread.cpp:34
#19 0x00007fffec57ab45 in QObject::event(QEvent*) () from /home/rwagner/Qt/6.3.1/gcc_64/lib/libQt6Core.so.6
--Type <RET> for more, q to quit, c to continue without paging--
#20 0x00007fffecdabf85 in QGuiApplication::event(QEvent*) () from /home/rwagner/Qt/6.3.1/gcc_64/lib/libQt6Gui.so.6
#21 0x00007ffff718c793 in QApplication::event(QEvent*) () from /home/rwagner/Qt/6.3.1/gcc_64/lib/libQt6Widgets.so.6
#22 0x00007ffff7183d46 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/rwagner/Qt/6.3.1/gcc_64/lib/libQt6Widgets.so.6
#23 0x00007ffff718f030 in QApplication::notify(QObject*, QEvent*) ()
   from /home/rwagner/Qt/6.3.1/gcc_64/lib/libQt6Widgets.so.6
#24 0x00007fffec528c8a in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /home/rwagner/Qt/6.3.1/gcc_64/lib/libQt6Core.so.6
#25 0x00007fffec52bf14 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /home/rwagner/Qt/6.3.1/gcc_64/lib/libQt6Core.so.6
#26 0x00007fffec6c54c1 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/rwagner/Qt/6.3.1/gcc_64/lib/libQt6Core.so.6
#27 0x00007fffe8d9f3d2 in QXcbUnixEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/rwagner/Qt/6.3.1/gcc_64/plugins/platforms/../../lib/libQt6XcbQpa.so.6
#28 0x00007fffec534aab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/rwagner/Qt/6.3.1/gcc_64/lib/libQt6Core.so.6
#29 0x00007fffec530576 in QCoreApplication::exec() () from /home/rwagner/Qt/6.3.1/gcc_64/lib/libQt6Core.so.6
#30 0x00005555555f6a6b in main (argc=<optimized out>, argv=<optimized out>)
    at /home/rwagner/projects/binaryninja/ui/main.cpp:2141
```

**Comment by xusheng6** [comment]
This probably gonna gets fixed by the fix for https://github.com/Vector35/debugger/issues/328

**Comment by xusheng6** [comment]
Closing this since #318 is fixed
