### ISSUE TITLE
`DebuggerController.write_stdin` calls into C API incorrectly

### ISSUE THREAD

**Issue by galenbwill** [Vector35/debugger#341]
```python
>>> dbg = debugger.DebuggerController(bv)
>>> dbg.write_stdin(b'\x01\x01\x01\x01\x01\x01')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File ".../binaryninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/debugger/debuggercontroller.py", line 1232, in write_stdin
    dbgcore.BNDebuggerWriteStdin(self.handle, data)
TypeError: BNDebuggerWriteStdin() missing 1 required positional argument: 'len'
>>> dbg.write_stdin(b'\x01\x01\x01\x01\x01\x01', 6)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: DebuggerController.write_stdin() takes 2 positional arguments but 3 were given
```

**Comment by xusheng6** [comment]
Thx for the fix!
