### ISSUE TITLE
Crash when stepping through code at fast pace

### ISSUE THREAD

**Issue by xusheng6** [Vector35/debugger#537]
We recently encounter a new crash when the user steps over very fast on an IL. The symbolicatd stack trace is:

```
Thread 154 "binaryninja" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f3e3f7fe640 (LWP 2077892)]
0x00007f3ea252c694 in BinaryNinja::HighLevelILFunction::GetInstructionCount() const () from /home/user/binaryninja/plugins/libdebuggercore.so
(gdb) bt
#0  0x00007f3ea252c694 in BinaryNinja::HighLevelILFunction::GetInstructionCount() const () from /home/user/binaryninja/plugins/libdebuggercore.so
#1  0x00007f3ea248f894 in BinaryNinjaDebugger::DebuggerController::StepIntoIL(BNFunctionGraphType) () from /home/user/binaryninja/plugins/libdebuggercore.so
#2  0x00007f3ea2490070 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<BinaryNinjaDebugger::DebuggerController::StepInto(BNFunctionGraphType)::{lambda()#1}> > >::_M_run() ()
   from /home/user/binaryninja/plugins/libdebuggercore.so
#3  0x00007f3eb58dc253 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f3eb5494ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007f3eb5526850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) pipe info sharedlibrary | grep libdebugger
0x00007f3ea2459190  0x00007f3ea25f921b  Yes (*)     /home/user/binaryninja/plugins/libdebuggercore.so
0x00007f3e8a070a00  0x00007f3e8a23491e  Yes (*)     /home/user/binaryninja/plugins/libdebuggerui.so
```

It is probably caused by a nullptr deref at: https://github.com/Vector35/debugger/blob/c839d245697c5e108208965629cfe0f4c3d4fd22/core/debuggercontroller.cpp#L428-L429

**Comment by xusheng6** [comment]
This is fixed in dev 4.6.4812.
