### ISSUE TITLE
host i/o packet did not start with F: b

### ISSUE THREAD

**Issue by numin0us** [Vector35/debugger#56]
Platform Information:
MacOS 11.6 (20G165) (M1) 

Application Version:
2.4.2846 Personal

I ran into an issue while attempting to use the debugger plugin with a cross-compiled binary run through qemu-user and an exposed gdbserver port. 

In a VM I ran the following command
`qemu-i386 -L /usr/i686-linux-gnu -g 1234 ./dragon`

In Binja I connected to the host using the REMOTE_GDB protocol and get a prompt to enter the path for the binary. After entering the path I receive the following error. 

I subsequently attempted to use `gdb-multiarch` and was able to connect to the qemu-user run binary and debug as normal. 

```
Detected remote process running at different path: /home/parallels/projects/ctfs/dragon/dragon
Traceback (most recent call last):
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/binjaplug.py", line 387, in apply
    remote_address = self.state.modules.relative_addr_to_absolute(bp)
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/binjaplug.py", line 262, in relative_addr_to_absolute
    if self[module]:
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/binjaplug.py", line 230, in __getitem__
    for (modpath, modaddr) in self:
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/binjaplug.py", line 222, in __iter__
    self.update()
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/binjaplug.py", line 218, in update
    self.module_cache = self.state.adapter.mem_modules().items()
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 186, in mem_modules
    return self.submit(lambda: self.adapter.mem_modules(cache_ok))
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 84, in submit
    raise result
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 48, in worker
    self.results[index] = (True, job())
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 186, in <lambda>
    return self.submit(lambda: self.adapter.mem_modules(cache_ok))
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/gdb.py", line 96, in mem_modules
    data = self.get_remote_file(fpath)
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/gdblike.py", line 457, in get_remote_file
    (result, errno, attachment) = self.rspConn.tx_rx('vFile:setfs:0', 'host_io')
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/rsp.py", line 109, in tx_rx
    raise RspGeneralError('host i/o packet did not start with F: ' + str(reply))
Vector35_debugger.rsp.RspGeneralError: host i/o packet did not start with F: b''
Exception ignored on calling ctypes callback function: <function _ThreadActionContext.__init__.<locals>.<lambda> at 0x1830c1af0>
Traceback (most recent call last):
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/scriptingprovider.py", line 57, in <lambda>
    self.callback = ctypes.CFUNCTYPE(None, ctypes.c_void_p)(lambda ctxt: self.execute())
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/scriptingprovider.py", line 65, in execute
    self.func()
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/dockwidgets/ControlsWidget.py", line 324, in perform_attach_after
    self.debug_state.ui.on_step()
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/ui.py", line 175, in on_step
    self.detect_new_code()
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/ui.py", line 253, in detect_new_code
    local_rip = self.state.local_ip
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/binjaplug.py", line 489, in local_ip
    return self.memory_view.remote_addr_to_local(self.ip)
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/ProcessView.py", line 101, in remote_addr_to_local
    remote_base = self.get_remote_base(relative_view)
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/ProcessView.py", line 62, in get_remote_base
    base = debug_state.modules[module]
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/binjaplug.py", line 230, in __getitem__
    for (modpath, modaddr) in self:
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/binjaplug.py", line 222, in __iter__
    self.update()
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/binjaplug.py", line 218, in update
    self.module_cache = self.state.adapter.mem_modules().items()
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 186, in mem_modules
    return self.submit(lambda: self.adapter.mem_modules(cache_ok))
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 84, in submit
    raise result
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 48, in worker
    self.results[index] = (True, job())
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/QueuedAdapter.py", line 186, in <lambda>
    return self.submit(lambda: self.adapter.mem_modules(cache_ok))
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/gdb.py", line 96, in mem_modules
    data = self.get_remote_file(fpath)
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/gdblike.py", line 457, in get_remote_file
    (result, errno, attachment) = self.rspConn.tx_rx('vFile:setfs:0', 'host_io')
  File "/Users/adi/Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/rsp.py", line 109, in tx_rx
    raise RspGeneralError('host i/o packet did not start with F: ' + str(reply))
Vector35_debugger.rsp.RspGeneralError: host i/o packet did not start with F: b''
```

**Comment by xusheng6** [comment]
The debugger is written in a way that assumes the remote file system exists -- we try to read the /dev/pid/maps from it to determine the list of loaded modules. We should be more cautious about this assumption, and come up with a more universal way of determining the modules.

**Comment by xusheng6** [comment]
No longer affects the native debugger
