### ISSUE TITLE
It stops working using remote debugging

### ISSUE THREAD

**Issue by SpaceComet** [Vector35/debugger#62]
I'm trying to debug a program in a router. I'm using gdbserver for this. 
When I connect with Binja everything seams to work normally but when the target program receive a request 
the debugger in Binary ninja stops working, and It print this on the log.

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 237, in 'calling callback function'
  File "C:\Users\someUser\AppData\Local\Vector35\BinaryNinja\plugins\..\python\binaryninja\scriptingprovider.py", line 51, in <lambda>
    self.callback = ctypes.CFUNCTYPE(None, ctypes.c_void_p)(lambda ctxt: self.execute())
  File "C:\Users\someUser\AppData\Local\Vector35\BinaryNinja\plugins\..\python\binaryninja\scriptingprovider.py", line 59, in execute
    self.func()
  File "C:\Users\someUser\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\dockwidgets\ControlsWidget.py", line 355, in <lambda>
    execute_on_main_thread_and_wait(lambda: perform_resume_after(reason, data))
  File "C:\Users\someUser\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\dockwidgets\ControlsWidget.py", line 359, in perform_resume_after
    self.debug_state.ui.on_step()
  File "C:\Users\someUser\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\ui.py", line 169, in on_step
    self.context_display()
  File "C:\Users\someUser\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\ui.py", line 97, in context_display
    threads = list(self.state.threads)
  File "C:\Users\someUser\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\binjaplug.py", line 166, in __iter__
    self.update()
  File "C:\Users\someUser\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\binjaplug.py", line 144, in update
    self.state.adapter.thread_select(tid)
  File "C:\Users\someUser\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\QueuedAdapter.py", line 153, in thread_select
    return self.submit(lambda: self.adapter.thread_select(tidx))
  File "C:\Users\someUser\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\QueuedAdapter.py", line 84, in submit
    raise result
  File "C:\Users\someUser\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\QueuedAdapter.py", line 48, in worker
    self.results[index] = (True, job())
  File "C:\Users\someUser\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\QueuedAdapter.py", line 153, in <lambda>
    return self.submit(lambda: self.adapter.thread_select(tidx))
  File "C:\Users\someUser\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_debugger\gdblike.py", line 230, in thread_select
    raise DebugAdapter.GeneralError('setting tid 0x%X for step and continue' % tid)
Vector35_debugger.DebugAdapter.GeneralError: setting tid 0x534E for step and continue
```

**Comment by xusheng6** [comment]
No longer affecting the native debugger
