### ISSUE TITLE
Error message when trying to install WinDbg/DbgEng 

### ISSUE THREAD

**Issue by xusheng6** [Vector35/debugger#651]
```
Script "C:\Users\user\AppData\Local\Vector35\BinaryNinja\plugins\dbgeng\install_windbg.py" successfully started execution.
Downloading appinstaller from: https://aka.ms/windbg/download...
Successfully downloaded appinstaller
Downloading MSIX bundle from: https://windbg.download.prss.microsoft.com/dbazure/prod/1-2410-11001-0/windbg.msixbundle...
Successfully downloaded MSIX bundle
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Vector35\BinaryNinja\plugins\dbgeng\install_windbg.py", line 85, in <module>
    install_windbg()
  File "C:\Users\user\AppData\Local\Vector35\BinaryNinja\plugins\dbgeng\install_windbg.py", line 62, in install_windbg
    inner_msix = zip_file.extract('windbg_win7-x64.msix', temp_dir)
  File "zipfile.py", line 1628, in extract
  File "zipfile.py", line 1667, in _extract_member
  File "zipfile.py", line 1441, in getinfo
KeyError: "There is no item named 'windbg_win7-x64.msix' in the archive"
```

The user was able to fix it by changing `inner_msix = zip_file.extract('windbg_win7-x64.msix', temp_dir)` to `inner_msix = zip_file.extract('windbg_win-x64.msix', temp_dir)`, apparently Microsoft changed the name of the file

**Comment by xusheng6** [comment]
We also need to:

1. Add a script in the nightly test to monitor the WinDbg/DbgEng can be correctly downloaded and installed
2. Offer a way to update the installed WinDbg/DbgEng

**Comment by xusheng6** [comment]
Fixed by https://github.com/Vector35/debugger/commit/a3a01f9c174dec6c13be94631b733251e8e95331
